<?php

namespace TradusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdditionalServicesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalServicesRepository extends EntityRepository
{
    public function getServicesIds()
    {
    }
}
