<?php

namespace TradusBundle\Repository;

/**
 * ApolloRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApolloRepository extends \Doctrine\ORM\EntityRepository
{
}
