<?php

namespace TradusBundle\Repository;

/**
 * ApolloBatchRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApolloBatchRepository extends \Doctrine\ORM\EntityRepository
{
}
