<?php

namespace TradusBundle\Repository;

/**
 * AttributeTranslationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
