<?php

namespace TradusBundle\Repository;

/**
 * CategoryRedirectRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRedirectRepository extends \Doctrine\ORM\EntityRepository
{
}
