<?php

namespace TradusBundle\Repository;

use TradusBundle\Entity\Country;

/**
 * CountryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function getTopCountries()
    {
        $topCountries = $this->createQueryBuilder('country')
            ->select('country.isoCode')
            ->where('country.topCountry= :status')
            ->setParameter('status', Country::IS_TOP_COUNTRY)
            ->getQuery();

        return $topCountries->getResult();
    }
}
