<?php

namespace TradusBundle\Repository;

/**
 * EmailJournalRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailJournalRepository extends \Doctrine\ORM\EntityRepository
{
}
