<?php

namespace TradusBundle\Repository;

use DateTime;

/**
 * JournalRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get latest action performed by the user by action in X past time.
     *
     * @param string $action
     * @param string $time http://php.net/manual/en/datetime.modify.php
     * @return mixed
     *
     * @throws NonUniqueResultException
     */
    public function getLatestByActionAndPastTime(string $action, string $time)
    {
        $interval = new DateTime();
        $interval->modify($time);

        $latestAction = $this->createQueryBuilder('journal')
            ->select('journal')
            ->where('journal.action = :action')
            ->andWhere('journal.createdAt >= :interval')
            ->setParameter('action', $action)
            ->setParameter('interval', $interval)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $latestAction;
    }
}
