<?php

namespace TradusBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * OfferAnalyticsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAnalyticsRepository extends EntityRepository
{
    /**
     * @param int $offerId
     * @param int $sitecodeId
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function getAnalyticsByWL(int $offerId, int $sitecodeId)
    {
        $query = $this->createQueryBuilder('offer_analytics')
            ->select('offer_analytics')
            ->where('offer_analytics.offer= :offer')
            ->andWhere('offer_analytics.sitecode_id= :sitecode')
            ->setMaxResults(1)
            ->setParameter('offer', $offerId)
            ->setParameter('sitecode', $sitecodeId);

        return $query->getQuery()->getOneOrNullResult();
    }
}
