<?php

namespace TradusBundle\Repository;

/**
 * OfferDescriptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
