<?php

namespace TradusBundle\Repository;

/**
 * OfferTitleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
