<?php

namespace TradusBundle\Repository;

/**
 * OfferShippingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferShippingRepository extends \Doctrine\ORM\EntityRepository
{
}
