<?php

namespace TradusBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TradusBundle\Service\Sitecode\SitecodeService;

/**
 * SearchAnalyticsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchAnalyticsRepository extends EntityRepository
{
    /**
     * @param array $param
     * @return mixed
     */
    public function getSearchAnalytics(array $param)
    {
        $scs = new SitecodeService();
        $sitecodeId = $scs->getSitecodeId();

        return $this->createQueryBuilder('analytics')
            ->where('analytics.queryString = :queryString')
            ->andWhere('analytics.country = :country')
            ->andWhere('analytics.keyword = :keyword')
            ->andWhere('analytics.sitecodeId = :sitecodeId')
            ->setParameter('country', $param['country'])
            ->setParameter('queryString', $param['queryString'])
            ->setParameter('keyword', $param['keyword'])
            ->setParameter('sitecodeId', $sitecodeId)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
