<?php

namespace TradusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchGroupRepository extends EntityRepository
{
}
