<?php

namespace TradusBundle\Repository;

/**
 * SellerPreferenceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
