<?php

namespace TradusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SellerSitecodeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerSitecodeRepository extends EntityRepository
{
    /**
     * @param string $slug
     * @return mixed
     */
    public function getSitecodesBySellerId(int $seller_id)
    {
        $query = $this->createQueryBuilder('seller_sitecodes')
            ->select('seller_sitecodes')
            ->andWhere('seller_sitecodes.sellerId = :id')
            ->setParameter('name', $seller_id);

        return $query->getQuery()->getResult();
    }
}
