<?php

namespace TradusBundle\Repository;

/**
 * TranslationLookupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationLookupRepository extends \Doctrine\ORM\EntityRepository
{
}
